version: '3'
services:
  # Node.js backend service
  backend:
    build: ./backend
    ports:
      - "5000:5000"

  # React frontend service
  frontend:
    build: ./frontend
    ports:
      - "80:80"

  # Python service with parameterized entrypoint
  python:
    build:
      context: ./python
      args:
        - PYTHON_FILE=your_script.py
    environment:
      - PYTHON_FILE=your_script.py

  # CockroachDB nodes
  crdb1:
    image: cockroachdb/cockroach:latest
    command: start --insecure --join=crdb1,crdb2,crdb3
    hostname: crdb1
    volumes:
      - crdb1-data:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"

  crdb2:
    image: cockroachdb/cockroach:v23.1.2
    command: start --insecure --join=crdb1,crdb2,crdb3
    hostname: crdb2
    volumes:
      - crdb2-data:/cockroach/cockroach-data
    ports:
      - "26258:26257"
      - "8081:8080"

  crdb3:
    image: cockroachdb/cockroach:v23.1.2
    command: start --insecure --join=crdb1,crdb2,crdb3
    hostname: crdb3
    volumes:
      - crdb3-data:/cockroach/cockroach-data
    ports:
      - "26259:26257"
      - "8082:8080"

  # HAProxy load balancer for CockroachDB
  haproxy:
    image: haproxy:latest
    depends_on:
      - crdb1
      - crdb2
      - crdb3
    ports:
      - "26256:26256"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

volumes:
  crdb1-data:
  crdb2-data:
  crdb3-data:
